CREATE DATABASE IF NOT EXISTS waterlift_solar CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE waterlift_solar;

CREATE TABLE admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- IMPORTANT: Do NOT use this file to seed the admin password.
-- Run this command instead to create the admin account with a correct hash:
--   php backend/setup_admin.php
--
-- (The placeholder below uses bcrypt for 'Waterlift2024!' — generated by setup_admin.php)
-- If you have already run setup_admin.php, skip this INSERT.
INSERT INTO admins (username, email, password_hash, full_name)
VALUES ('admin', 'admin@waterliftsolar.co.ke', '$2y$10$placeholder_run_setup_admin_php', 'Administrator')
ON DUPLICATE KEY UPDATE id=id; -- no-op if admin already exists

CREATE TABLE leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  school_name VARCHAR(200) NOT NULL,
  school_type ENUM('primary','secondary','boarding','polytechnic','university','other') NOT NULL,
  contact_name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(150),
  county VARCHAR(60),
  num_students INT,
  monthly_bill DECIMAL(10,2),
  preferred_plan VARCHAR(100),
  message TEXT,
  status ENUM('new','contacted','quoted','converted','closed') DEFAULT 'new',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE testimonials (
  id INT AUTO_INCREMENT PRIMARY KEY,
  author_name VARCHAR(100) NOT NULL,
  school_name VARCHAR(200),
  quote TEXT NOT NULL,
  rating TINYINT DEFAULT 5,
  photo_url VARCHAR(300),
  active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO testimonials (author_name, school_name, quote, rating, active) VALUES
('Mr. James Kamau', 'Sunrise Secondary School, Machakos', 'Since installing Waterlift Solar, our electricity bills dropped by 80%. Our labs and classrooms now run without interruption even during load shedding.', 5, 1),
('Sr. Agnes Wanjiru', 'St. Mary''s Girls Boarding, Nyeri', 'The water pumping system has been a game changer for us. No more diesel costs, no more dry taps. Our students are happy and our board is impressed.', 5, 1),
('Mr. Peter Otieno', 'Mombasa Technical Institute', 'Waterlift handled everything from assessment to installation in 3 weeks. Professional team, quality equipment, and the savings were visible from the first bill.', 5, 1);

CREATE TABLE faqs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  question VARCHAR(500) NOT NULL,
  answer TEXT NOT NULL,
  sort_order INT DEFAULT 0,
  active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO faqs (question, answer, sort_order, active) VALUES
('How much can our school save on electricity bills?', 'Most schools reduce their KPLC bills by 60–85% depending on system size and usage. Our free site audit will calculate your specific savings projection before you commit to anything.', 1, 1),
('Is there an upfront cost?', 'We offer flexible financing options including lease-to-own and performance contracts with zero upfront capital. Talk to our team to find the best fit for your school budget.', 2, 1),
('How long does installation take?', 'A typical school installation takes 3–7 days depending on system size. We work during school holidays or weekends to minimize disruption to learning.', 3, 1),
('What happens during a power outage?', 'Our systems include battery backup that keeps critical loads running — classrooms, labs, water pumps, and administration — even when KPLC power is down.', 4, 1),
('Do you handle maintenance?', 'Yes. All Waterlift systems include a maintenance agreement. We monitor system performance remotely and respond to issues within 24 hours.', 5, 1),
('Can the system power water pumps and boreholes?', 'Absolutely. We design solar-powered water systems specifically for school boreholes and storage tanks. This is one of our most requested services.', 6, 1);

CREATE TABLE site_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(100) NOT NULL UNIQUE,
  setting_value TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO site_settings (setting_key, setting_value) VALUES
('phone', '+254 700 000 000'),
('whatsapp', '+254700000000'),
('email', 'info@waterliftsolar.co.ke'),
('address', 'Nairobi, Kenya'),
('hero_headline', 'Cut Your School''s Power Bills by Up to 80%'),
('hero_subtext', 'Solar energy and water infrastructure solutions designed for Kenyan schools. Zero disruption, maximum savings, total reliability.');

CREATE TABLE calculator_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(100) NOT NULL UNIQUE,
  setting_value TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO calculator_settings (setting_key, setting_value) VALUES
('savings_percentage', '0.75'),
('installation_cost_per_kw', '85000'),
('avg_system_size_kw', '20'),
('payback_years', '4'),
('co2_per_kwh_kg', '0.51');
